config/routes.rb
Rails.application.routes.draw do

  root 'artists#index'

  post '/search' => 'artists#search'

    resources :artists
    resources :wordcounts

end

app/models/artist.rb
class Artist < ActiveRecord::Base
    has_many :wordcounts, dependent: :destroy
    validates :name, presence: true, uniqueness: true

    def self.normalize_name(name)
        name = name.downcase.gsub(/\s+/, ' ')
    end

    def self.get_wordcounts(artist)
        artist = normalize_name(artist)
        if !Artist.where(name: artist).exists?
            search_genius(artist)
        else
            return
        end
        # a_id = Artist.select('id').where(name: artist)
        # Wordcount.select('word, count').where(artist_id: a_id).order(count: :desc)
    end

    def self.search_genius(artist)

        # Find artist page
        agent = Mechanize.new
        artist_url = artist.gsub(' ', '-')
        begin
            page = agent.get('http://www.genius.com/artists/' + artist_url)
        rescue Mechanize::ResponseCodeError
            puts 'Artist not found'
            return
        end

        # Show entire page
        pagination_links = page.links_with(href: /for_artist_page/)
        pagination_links.each do |link|
            link.click
        end

        # Add new artist to database
        artist_object = create_artist(artist)

        # Click all song links
        song_links = page.links_with(href: /#{artist_url}.+lyrics/i)
        scrape_all_song_links(artist_object, artist, song_links, 4)
    end

    def self.create_artist(artist)
        a = Artist.where(name: artist)[0]
        if !a.nil?
            puts 'Artist already exists'
        else
            a = Artist.new(name: artist)
            begin
                a.save
                puts 'Artist saved: ' + artist
            rescue ActiveRecord::RecordNotUnique
                puts 'Already saved: ' + artist
            end
        end
        puts 'artist_id = ' + a.id.to_s
        return a
    end

    def self.scrape_all_song_links(artist_object, artist, song_links, range)
        puts "song links = " + song_links.to_s
        
        # Scrape all songs from {0...range}
        song_links[0...range].each do |link|
            song = link.click
            lyrics = song.css('p')[0].text.downcase.gsub(/\[.*\]/, '')
            word_array = lyrics.split(/\s+/) # find lyrics on page
            
            counts_hash = {} # count this song's word frequencies
            word_array.each do |word|
                word = word.gsub(/\W/, '')
                if counts_hash[word]
                    counts_hash[word] += 1
                else
                    counts_hash[word] = 1
                end
            end
            puts counts_hash

            # Add WC's to database
            insert_wordcounts(artist_object, counts_hash)
        end
    end

    def self.insert_wordcounts(artist_object, counts_hash)
		counts_hash.each do |word, count|
            w = Wordcount.where(word: word, artist_id: artist_object.id)[0]
            if !w.nil?
                w.count += count
            else
                w = Wordcount.new(word: word, count: count)
                w.artist = artist_object
			end

            begin
	            w.save
	            puts 'Saved word: ' + word + ', count: ' + count.to_s
	        rescue ActiveRecord::RecordNotUnique
	            puts 'Already saved: ' + word + ', count: ' + count.to_s
	        end
        end
    end
end

app/models/wordcount.rb
class Wordcount < ActiveRecord::Base
    belongs_to :artist
    validates :word, presence: true, uniqueness: {scope: :artist_id}
    validates :count, presence: true
    validates :artist_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
    
    def index
    	@artists = Artist.all
    end

    def show
        @fav_words = Wordcount.select('word, count').
                     where('artist_id = ?', params[:id]).
                     order(count: :desc)
        # @fav_words = Wordcount.select('word, count').
        #            where('artist_id = ? and length(word) >= ?',
        #            params[:id], params[:min].to_i).
        #            order(count: :desc).limit(8)
        # @longest_words = Wordcount.where(artist_id: params[:id]).
        #            order('length(word) desc').limit(8)
        @artist_name = Artist.where(id: params[:id])[0].name.titleize
        render json: {fav_words: @fav_words,
                      artist_name: @artist_name}
    end

    def search
        if Artist.get_wordcounts(params[:name]).nil?
            flash[:notice] = "Artist not found, or already in database"
        end
        redirect_to root_url
    end

    def destroy
        @artist = Artist.find(params[:id])
        @artist.destroy
        redirect_to root_url
    end

    private
        def artist_params
            params.require(:artist).permit(:name)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/scraper.rb
module Scraper

    def search_azlyrics(artist)
        agent = Mechanize.new
        artist = artist.gsub(' ', '')
        artist_url = artist[0] + '/' + artist + '.html'

        page = agent.get('http://azlyrics.com/' + artist_url)
        song_links = page.links_with(href: /lyrics\/#{artist}/)

        song = song_links[0].click
        lyrics = song.css('div.ringtone~div')[0].children

        lyrics.each do |line|
        end
    end
end

app/views/artists/_charts.html.erb
<div id="charts-container">
  <div id="chart-tabs">
    <div class="tab">
      <input type="radio" id="donut-chart-tab" name="choose-chart" checked>
      <label for="donut-chart-tab">Donut Chart</label>    
      <div class="chart-content" id="donut-chart" style="width:100%; height:400px;"></div>
    </div>

    <div class="tab">
      <input type="radio" id="bar-chart-tab" name="choose-chart">
      <label for="bar-chart-tab">Bar Chart</label>
      <div class="chart-content" id="bar-chart" style="width:100%; height:400px;"></div>
    </div>
  </div>
</div>

app/views/artists/_cloud.html.erb
<div id="cloud"></div>

app/views/artists/_front.html.erb
<header class="welcome-header">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <h1 class="tagline">Lyric Charts</h1>
      </div>
    </div>
  </div>
</header>

<div class="container">
  <div class="row">
    
    <div class="col-sm-4">
      <img class="img-circle img-responsive img-center" src="assets/db-icon.png" alt="">
      <h2>Artist Database</h2>
      <p>Look up your favorite artist in the massive database</p>
    </div>

    <div class="col-sm-4">
      <img class="img-circle img-responsive img-center" src="assets/chart-icon.png" alt="">
      <h2>Charts</h2>
      <p>Donut chart and bar chart provide different perspectives of the data</p>
    </div>

    <div class="col-sm-4">
      <img class="img-circle img-responsive img-center" src="assets/light-bulb-icon.png" alt="">
      <h2>Vocabulary</h2>
      <p>Filter data by word size</p>
    </div>
  
  </div>
</div>

app/views/artists/_header.html.erb
<div id="header-container">
  <%= form_tag("/search", method: "post") do %>  
    <%= label_tag(:name, "Search New Artist") %>
    <%= text_field_tag :name, params[:name], id: "artist-name-input" %>
    <%= submit_tag("Go!", id:"submit-artist-button") %>
  <% end %>

  <div><%= flash[:notice] %></div>
</div>

app/views/artists/_search.html.erb
<div id="search-container">
  <%= form_tag("/search", method: "post") do %>  
    <%= label_tag(:name, "Search New Artist") %>
    <%= text_field_tag :name, params[:name], id: "artist-name-input" %>
    <%= submit_tag("Go!", id:"submit-artist-button") %>
  <% end %>

  <div><%= flash[:notice] %></div>
</div>

app/views/artists/_sidebar.html.erb
<div id="sidebar-container">
  Minimum Word Length: <span id="min-display">5</span>
  <input type="range" min="1" max="10" id="min-word-length">
  <ul id="artist-list">Choose Artist
    <% @artists.each do |artist| %>
      <li>
        <button class="get-artist-button" name="<%= artist.id %>">
          <%= artist.name.titleize %>
        </button>
        <%= button_to "X", artist_path(artist.id), method: :delete, class: 'x-button' %>
      </li>
    <% end %>
  </ul>
</div>

app/views/artists/index.html.erb
<script src="http://code.highcharts.com/highcharts.js"></script>
<script src="http://code.highcharts.com/highcharts-3d.js"></script>
<!-- <script src="http://code.highcharts.com/highcharts-more.js"></script> -->

<%= render 'front' %>

<!--
<%= render 'search' %>
<%= render 'sidebar' %>
<%= render 'charts' %>
  -->
<div class="container">
  <div class="row">
    
    <div class="col-lg-2" id="search-container">
      <%= form_tag("/search", method: "post") do %>  
        <%= label_tag(:name, "Search New Artist") %>
        <%= text_field_tag :name, params[:name], id: "artist-name-input" %>
        <%= submit_tag("Go!", id:"submit-artist-button") %>
      <% end %>
      <div><%= flash[:notice] %></div>
    </div>

    <div class="col-lg-2" id="sidebar-container">
      
      <div class="row">
        <h4>Minimum Word Length: <span id="min-display">5</span></h4>
      </div>

      <input type="range" min="1" max="10" id="min-word-length">
      
      <div class="row">
        <h4>Choose Artist</h4>
      </div>

      <div class="row">
        <div class="col-lg-2 list-group" id="x-button-list">
          <% @artists.each do |artist| %>
              <%= button_to "X", artist_path(artist.id), method: :delete, class: "list-group-item" %>
          <% end %>
        </div>
        
        <div class="col-lg-10 list-group" id="artist-list">
          <% @artists.each do |artist| %>
              <button type="button" class="list-group-item get-artist-button" name="<%= artist.id %>">
                <%= artist.name.titleize %>
              </button>
          <% end %>
        </div>
      </div>
    </div>

    <div class="col-lg-8" id="charts-container">
      <div id="chart-tabs">
        <div class="tab">
          <input type="radio" id="donut-chart-tab" name="choose-chart" checked>
          <label for="donut-chart-tab">Donut Chart</label>    
          <div class="chart-content" id="donut-chart" style="width:100%; height:400px;"></div>
        </div>

        <div class="tab">
          <input type="radio" id="bar-chart-tab" name="choose-chart">
          <label for="bar-chart-tab">Bar Chart</label>
          <div class="chart-content" id="bar-chart" style="width:100%; height:400px;"></div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sean's Data Visualizations</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>